# Generated by Django 6.0.4 on 2026-04-16 11:03

import fileapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fileapp.models.upload_to)),
                ('unique_key', models.CharField(db_index=True, editable=False, max_length=6, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
