# Generated by Django 6.0.4 on 2026-04-16 12:09

import fileapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='expires_at',
            field=models.DateTimeField(default=fileapp.models.default_expires_at, editable=False),
        ),
    ]
